apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-boom
  namespace: default
  labels:
    app: wiki-boom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiki-boom
  template:
    metadata:
      labels:
        app: wiki-boom
    spec:
      containers:
      - name: front-end
        image: werta/wiki_boom:front_end
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8989
        env:
          # Use secret in real usage
        - name: SQL_HOST
          value: db
        livenessProbe:
          httpGet:
            port: 8989
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
      - name: db
        image: postgres:latest
        env:
          # Use secret in real usage
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
