apiVersion: v1
kind: Service
metadata:
  name: wiki-boom
spec:
  type: NodePort
  selector:
    app: wiki-boom
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8000
      targetPort: 8000
